spring:
  jersey:
    application-path: /engine-rest
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./testDB
    username: SA
    password: SA
camunda.bpm.admin-user:
  id: admin
  password: admin